-- Generated by protobuf-simple. DO NOT EDIT!
module Types.BytesList where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype BytesList = BytesList
  { value :: PB.Seq PB.ByteString
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default BytesList where
  defaultVal = BytesList
    { value = PB.defaultVal
    }

instance PB.Mergeable BytesList where
  merge a b = BytesList
    { value = PB.merge (value a) (value b)
    }

instance PB.Required BytesList where
  reqTags _ = PB.fromList []

instance PB.WireMessage BytesList where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{value = PB.append (value self) v}) <$> PB.getBytes
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putBytesList (PB.WireTag 1 PB.LenDelim) (value self)


