-- Generated by protobuf-simple. DO NOT EDIT!
module Types.BytesMsg where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype BytesMsg = BytesMsg
  { value :: PB.ByteString
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default BytesMsg where
  defaultVal = BytesMsg
    { value = PB.defaultVal
    }

instance PB.Mergeable BytesMsg where
  merge a b = BytesMsg
    { value = PB.merge (value a) (value b)
    }

instance PB.Required BytesMsg where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.LenDelim]

instance PB.WireMessage BytesMsg where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getBytes
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putBytes (PB.WireTag 1 PB.LenDelim) (value self)


