-- Generated by protobuf-simple. DO NOT EDIT!
module Types.DoubleList where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype DoubleList = DoubleList
  { value :: PB.Seq PB.Double
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default DoubleList where
  defaultVal = DoubleList
    { value = PB.defaultVal
    }

instance PB.Mergeable DoubleList where
  merge a b = DoubleList
    { value = PB.merge (value a) (value b)
    }

instance PB.Required DoubleList where
  reqTags _ = PB.fromList []

instance PB.WireMessage DoubleList where
  fieldToValue (PB.WireTag 1 PB.Bit64) self = (\v -> self{value = PB.append (value self) v}) <$> PB.getDouble
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putDoubleList (PB.WireTag 1 PB.Bit64) (value self)


