-- Generated by protobuf-simple. DO NOT EDIT!
module Types.Enum where

import Prelude ()
import qualified Data.ProtoBufInt as PB

data Enum = Zero | One | Two | Three | Four | Five | Six | Seven | Eight | Nine
  deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default Enum where
  defaultVal = Zero

instance PB.Mergeable Enum where

instance PB.WireEnum Enum where
  intToEnum 0 = Zero
  intToEnum 1 = One
  intToEnum 2 = Two
  intToEnum 3 = Three
  intToEnum 4 = Four
  intToEnum 5 = Five
  intToEnum 6 = Six
  intToEnum 7 = Seven
  intToEnum 8 = Eight
  intToEnum 9 = Nine
  intToEnum _ = PB.defaultVal

  enumToInt Zero = 0
  enumToInt One = 1
  enumToInt Two = 2
  enumToInt Three = 3
  enumToInt Four = 4
  enumToInt Five = 5
  enumToInt Six = 6
  enumToInt Seven = 7
  enumToInt Eight = 8
  enumToInt Nine = 9


