-- Generated by protobuf-simple. DO NOT EDIT!
module Types.EnumListPacked where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified Types.Enum

newtype EnumListPacked = EnumListPacked
  { value :: PB.Seq Types.Enum.Enum
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default EnumListPacked where
  defaultVal = EnumListPacked
    { value = PB.defaultVal
    }

instance PB.Mergeable EnumListPacked where
  merge a b = EnumListPacked
    { value = PB.merge (value a) (value b)
    }

instance PB.Required EnumListPacked where
  reqTags _ = PB.fromList []

instance PB.WireMessage EnumListPacked where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getEnumPacked
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{value = PB.append (value self) v}) <$> PB.getEnum
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putEnumPacked (PB.WireTag 1 PB.LenDelim) (value self)


