-- Generated by protobuf-simple. DO NOT EDIT!
module Types.Fixed64List where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype Fixed64List = Fixed64List
  { value :: PB.Seq PB.Word64
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default Fixed64List where
  defaultVal = Fixed64List
    { value = PB.defaultVal
    }

instance PB.Mergeable Fixed64List where
  merge a b = Fixed64List
    { value = PB.merge (value a) (value b)
    }

instance PB.Required Fixed64List where
  reqTags _ = PB.fromList []

instance PB.WireMessage Fixed64List where
  fieldToValue (PB.WireTag 1 PB.Bit64) self = (\v -> self{value = PB.append (value self) v}) <$> PB.getFixed64
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putFixed64List (PB.WireTag 1 PB.Bit64) (value self)


