-- Generated by protobuf-simple. DO NOT EDIT!
module Types.Fixed32OptMsg where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype Fixed32OptMsg = Fixed32OptMsg
  { value :: PB.Maybe PB.Word32
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default Fixed32OptMsg where
  defaultVal = Fixed32OptMsg
    { value = PB.defaultVal
    }

instance PB.Mergeable Fixed32OptMsg where
  merge a b = Fixed32OptMsg
    { value = PB.merge (value a) (value b)
    }

instance PB.Required Fixed32OptMsg where
  reqTags _ = PB.fromList []

instance PB.WireMessage Fixed32OptMsg where
  fieldToValue (PB.WireTag 1 PB.Bit32) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getFixed32Opt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putFixed32Opt (PB.WireTag 1 PB.Bit32) (value self)


