-- Generated by protobuf-simple. DO NOT EDIT!
module Types.Fixed64OptMsg where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype Fixed64OptMsg = Fixed64OptMsg
  { value :: PB.Maybe PB.Word64
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default Fixed64OptMsg where
  defaultVal = Fixed64OptMsg
    { value = PB.defaultVal
    }

instance PB.Mergeable Fixed64OptMsg where
  merge a b = Fixed64OptMsg
    { value = PB.merge (value a) (value b)
    }

instance PB.Required Fixed64OptMsg where
  reqTags _ = PB.fromList []

instance PB.WireMessage Fixed64OptMsg where
  fieldToValue (PB.WireTag 1 PB.Bit64) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getFixed64Opt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putFixed64Opt (PB.WireTag 1 PB.Bit64) (value self)


