-- Generated by protobuf-simple. DO NOT EDIT!
module Types.Fixed64ListPacked where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype Fixed64ListPacked = Fixed64ListPacked
  { value :: PB.Seq PB.Word64
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default Fixed64ListPacked where
  defaultVal = Fixed64ListPacked
    { value = PB.defaultVal
    }

instance PB.Mergeable Fixed64ListPacked where
  merge a b = Fixed64ListPacked
    { value = PB.merge (value a) (value b)
    }

instance PB.Required Fixed64ListPacked where
  reqTags _ = PB.fromList []

instance PB.WireMessage Fixed64ListPacked where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getFixed64Packed
  fieldToValue (PB.WireTag 1 PB.Bit64) self = (\v -> self{value = PB.append (value self) v}) <$> PB.getFixed64
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putFixed64Packed (PB.WireTag 1 PB.LenDelim) (value self)


