-- Generated by protobuf-simple. DO NOT EDIT!
module Types.Int32List where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype Int32List = Int32List
  { value :: PB.Seq PB.Int32
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default Int32List where
  defaultVal = Int32List
    { value = PB.defaultVal
    }

instance PB.Mergeable Int32List where
  merge a b = Int32List
    { value = PB.merge (value a) (value b)
    }

instance PB.Required Int32List where
  reqTags _ = PB.fromList []

instance PB.WireMessage Int32List where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{value = PB.append (value self) v}) <$> PB.getInt32
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putInt32List (PB.WireTag 1 PB.VarInt) (value self)


