-- Generated by protobuf-simple. DO NOT EDIT!
module Types.SFixed32Msg where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype SFixed32Msg = SFixed32Msg
  { value :: PB.Int32
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default SFixed32Msg where
  defaultVal = SFixed32Msg
    { value = PB.defaultVal
    }

instance PB.Mergeable SFixed32Msg where
  merge a b = SFixed32Msg
    { value = PB.merge (value a) (value b)
    }

instance PB.Required SFixed32Msg where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.Bit32]

instance PB.WireMessage SFixed32Msg where
  fieldToValue (PB.WireTag 1 PB.Bit32) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getSFixed32
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putSFixed32 (PB.WireTag 1 PB.Bit32) (value self)


