-- Generated by protobuf-simple. DO NOT EDIT!
module Types.SFixed32ListPacked where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype SFixed32ListPacked = SFixed32ListPacked
  { value :: PB.Seq PB.Int32
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default SFixed32ListPacked where
  defaultVal = SFixed32ListPacked
    { value = PB.defaultVal
    }

instance PB.Mergeable SFixed32ListPacked where
  merge a b = SFixed32ListPacked
    { value = PB.merge (value a) (value b)
    }

instance PB.Required SFixed32ListPacked where
  reqTags _ = PB.fromList []

instance PB.WireMessage SFixed32ListPacked where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getSFixed32Packed
  fieldToValue (PB.WireTag 1 PB.Bit32) self = (\v -> self{value = PB.append (value self) v}) <$> PB.getSFixed32
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putSFixed32Packed (PB.WireTag 1 PB.LenDelim) (value self)


