-- Generated by protobuf-simple. DO NOT EDIT!
module Types.SFixed64ListPacked where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype SFixed64ListPacked = SFixed64ListPacked
  { value :: PB.Seq PB.Int64
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default SFixed64ListPacked where
  defaultVal = SFixed64ListPacked
    { value = PB.defaultVal
    }

instance PB.Mergeable SFixed64ListPacked where
  merge a b = SFixed64ListPacked
    { value = PB.merge (value a) (value b)
    }

instance PB.Required SFixed64ListPacked where
  reqTags _ = PB.fromList []

instance PB.WireMessage SFixed64ListPacked where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getSFixed64Packed
  fieldToValue (PB.WireTag 1 PB.Bit64) self = (\v -> self{value = PB.append (value self) v}) <$> PB.getSFixed64
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putSFixed64Packed (PB.WireTag 1 PB.LenDelim) (value self)


