-- Generated by protobuf-simple. DO NOT EDIT!
module Types.SFixed64OptMsg where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype SFixed64OptMsg = SFixed64OptMsg
  { value :: PB.Maybe PB.Int64
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default SFixed64OptMsg where
  defaultVal = SFixed64OptMsg
    { value = PB.defaultVal
    }

instance PB.Mergeable SFixed64OptMsg where
  merge a b = SFixed64OptMsg
    { value = PB.merge (value a) (value b)
    }

instance PB.Required SFixed64OptMsg where
  reqTags _ = PB.fromList []

instance PB.WireMessage SFixed64OptMsg where
  fieldToValue (PB.WireTag 1 PB.Bit64) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getSFixed64Opt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putSFixed64Opt (PB.WireTag 1 PB.Bit64) (value self)


