-- Generated by protobuf-simple. DO NOT EDIT!
module Types.SInt64List where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype SInt64List = SInt64List
  { value :: PB.Seq PB.Int64
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default SInt64List where
  defaultVal = SInt64List
    { value = PB.defaultVal
    }

instance PB.Mergeable SInt64List where
  merge a b = SInt64List
    { value = PB.merge (value a) (value b)
    }

instance PB.Required SInt64List where
  reqTags _ = PB.fromList []

instance PB.WireMessage SInt64List where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{value = PB.append (value self) v}) <$> PB.getSInt64
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putSInt64List (PB.WireTag 1 PB.VarInt) (value self)


