-- Generated by protobuf-simple. DO NOT EDIT!
module Types.SInt32List where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype SInt32List = SInt32List
  { value :: PB.Seq PB.Int32
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default SInt32List where
  defaultVal = SInt32List
    { value = PB.defaultVal
    }

instance PB.Mergeable SInt32List where
  merge a b = SInt32List
    { value = PB.merge (value a) (value b)
    }

instance PB.Required SInt32List where
  reqTags _ = PB.fromList []

instance PB.WireMessage SInt32List where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{value = PB.append (value self) v}) <$> PB.getSInt32
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putSInt32List (PB.WireTag 1 PB.VarInt) (value self)


