-- Generated by protobuf-simple. DO NOT EDIT!
module Types.SInt64ListPacked where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype SInt64ListPacked = SInt64ListPacked
  { value :: PB.Seq PB.Int64
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default SInt64ListPacked where
  defaultVal = SInt64ListPacked
    { value = PB.defaultVal
    }

instance PB.Mergeable SInt64ListPacked where
  merge a b = SInt64ListPacked
    { value = PB.merge (value a) (value b)
    }

instance PB.Required SInt64ListPacked where
  reqTags _ = PB.fromList []

instance PB.WireMessage SInt64ListPacked where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getSInt64Packed
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{value = PB.append (value self) v}) <$> PB.getSInt64
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putSInt64Packed (PB.WireTag 1 PB.LenDelim) (value self)


