-- Generated by protobuf-simple. DO NOT EDIT!
module Types.SInt32Msg where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype SInt32Msg = SInt32Msg
  { value :: PB.Int32
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default SInt32Msg where
  defaultVal = SInt32Msg
    { value = PB.defaultVal
    }

instance PB.Mergeable SInt32Msg where
  merge a b = SInt32Msg
    { value = PB.merge (value a) (value b)
    }

instance PB.Required SInt32Msg where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.VarInt]

instance PB.WireMessage SInt32Msg where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getSInt32
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putSInt32 (PB.WireTag 1 PB.VarInt) (value self)


