-- Generated by protobuf-simple. DO NOT EDIT!
module Types.SInt32OptMsg where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype SInt32OptMsg = SInt32OptMsg
  { value :: PB.Maybe PB.Int32
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default SInt32OptMsg where
  defaultVal = SInt32OptMsg
    { value = PB.defaultVal
    }

instance PB.Mergeable SInt32OptMsg where
  merge a b = SInt32OptMsg
    { value = PB.merge (value a) (value b)
    }

instance PB.Required SInt32OptMsg where
  reqTags _ = PB.fromList []

instance PB.WireMessage SInt32OptMsg where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getSInt32Opt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putSInt32Opt (PB.WireTag 1 PB.VarInt) (value self)


