-- Generated by protobuf-simple. DO NOT EDIT!
module Types.UInt32Msg where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype UInt32Msg = UInt32Msg
  { value :: PB.Word32
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default UInt32Msg where
  defaultVal = UInt32Msg
    { value = PB.defaultVal
    }

instance PB.Mergeable UInt32Msg where
  merge a b = UInt32Msg
    { value = PB.merge (value a) (value b)
    }

instance PB.Required UInt32Msg where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.VarInt]

instance PB.WireMessage UInt32Msg where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getUInt32
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putUInt32 (PB.WireTag 1 PB.VarInt) (value self)


