-- Generated by protobuf-simple. DO NOT EDIT!
module Types.UInt64List where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype UInt64List = UInt64List
  { value :: PB.Seq PB.Word64
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default UInt64List where
  defaultVal = UInt64List
    { value = PB.defaultVal
    }

instance PB.Mergeable UInt64List where
  merge a b = UInt64List
    { value = PB.merge (value a) (value b)
    }

instance PB.Required UInt64List where
  reqTags _ = PB.fromList []

instance PB.WireMessage UInt64List where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{value = PB.append (value self) v}) <$> PB.getUInt64
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putUInt64List (PB.WireTag 1 PB.VarInt) (value self)


